# Travis matrix for cross-platform and cross-version testing.
#
# See: https://github.com/brandtbucher/travis-python-matrix

matrix:
  include:
    - name: CPython 3.8.1 -- Ubuntu 18.04
      language: python
      os: linux
      dist: bionic
      python: 3.8

install:
- pip install -r deps/dev-requirements.txt

script:
- pwd; which python
- python tasks.py test
- flake8 .
- mypy .